# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'crgar Internal Subscription(930c11b0-5e6d-458f-b9e3-f3dda0734110)'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      Install-Module Az -Force -confirm:$false -AllowClobber
    useGlobalConfig: true

- task: AzureCLI@2
  inputs:
    azureSubscription: 'crgar Internal Subscription(930c11b0-5e6d-458f-b9e3-f3dda0734110)'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      Import-Module ./DeployLandingZone/deployment.psm1 -Verbose -Force
      New-SecureAksLandingZone -Verbose
    useGlobalConfig: true

- task: AzureCLI@2
  inputs:
    azureSubscription: 'crgar Internal Subscription(930c11b0-5e6d-458f-b9e3-f3dda0734110)'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      Import-Module ./DeployAksCni/SecureAks.psm1 -Verbose -Force
      New-SecureAksDeploymentInLandingZone -Verbose
    useGlobalConfig: true
